name: wallet
description: "Beautiful wallet to keep cards locally."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  barcode_widget: ^2.0.4
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  flutter_file_dialog: ^3.0.2
  google_fonts: ^6.1.0
  dynamic_color: ^1.6.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/swiggy.png
    - assets/swiggy_back.png
    - assets/simply_click.png
    - assets/simply_click_back.png
    - assets/default.jpg
    - assets/jnu_logo.png
