name: wallet
description: "Beautiful wallet to keep cards locally."
publish_to: 'none'


version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  barcode_widget: ^2.0.4
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  flutter_file_dialog: ^3.0.2
  google_fonts: ^6.1.0
  dynamic_color: ^1.6.3
  drift: ^2.11.0
  path_provider: ^2.0.11
  path: ^1.8.2
  sqlcipher_flutter_libs: ^0.6.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  crypto: ^3.0.3
  local_auth: ^2.2.0
  otp: ^3.0.1
  base32: ^2.1.3
  #  qr_code_scanner: ^1.0.1
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  encrypt: ^5.0.3
  file_picker: ^8.0.0+1
  #  path_provider: ^2.0.11 # Should already be there
  #  path: ^1.8.3 # Should already be there
  pointycastle: ^3.7.3
flutter_icons:
  android: true
  image_path: "assets/icon.png"
  min_sdk_android: 21


dev_dependencies:
  drift_dev: ^2.11.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/swiggy.png
    - assets/swiggy_back.png
    - assets/simply_click.png
    - assets/simply_click_back.png
    - assets/default.jpg
    - assets/jnu_logo.png
